//
// Copyright (c) .NET Foundation and Contributors
// See LICENSE file in the project root for full license information.
//
#include "nf_runtime_isr_core.h"

// clang-format off

static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::DoAllocateMemory___BOOLEAN__nanoFrameworkRuntimeISRInterpreterMemoryType__U4,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::AssignMemory___VOID__nanoFrameworkRuntimeISRInterpreterMemoryType__U4__SZARRAY_U1,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::AssignOffset___VOID__nanoFrameworkRuntimeISRInterpreterMemoryType__U4__U4,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::IsOffsetAssigned___BOOLEAN__nanoFrameworkRuntimeISRInterpreterMemoryType__U4,
    NULL,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::GetMemoryPointer___I4__nanoFrameworkRuntimeISRInterpreterMemoryType__U4,
    NULL,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::DoReadMemory___VOID__nanoFrameworkRuntimeISRInterpreterMemoryType__U4__SZARRAY_U1,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::ReleaseMemory___VOID,
    NULL,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::DoStartServiceRoutine___VOID__nanoFrameworkRuntimeISROnManagedActivation__BOOLEAN,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::StopManagedActivatedServiceRoutine___VOID,
    NULL,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::DoEnableRTOSTask___VOID,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::DisableRTOSTask___VOID,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::DataBuffer_GetMemorySize___U4__U4__U2,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::DataBuffer_Initialize___VOID__I4__U4__U2,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::DataBuffer_Capacity___U4__I4,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::DataBuffer_Count___U4__I4,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::DataBuffer_Add___VOID__I4__SZARRAY_U1,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::DataBuffer_Insert___VOID__I4__U4__SZARRAY_U1,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::DataBuffer_Get___VOID__I4__U4__SZARRAY_U1,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::DataBuffer_Clear___VOID__I4,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::DataRingBuffer_GetMemorySize___U4__U4__U2,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::DataRingBuffer_Initialize___VOID__I4__U4__U2,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::DataRingBuffer_Capacity___U4__I4,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::DataRingBuffer_IsEmpty___BOOLEAN__I4,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::DataRingBuffer_Push___BOOLEAN__I4__SZARRAY_U1__BOOLEAN,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::DataRingBuffer_Peek___BOOLEAN__I4__SZARRAY_U1,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::DataRingBuffer_Pop___BOOLEAN__I4__SZARRAY_U1,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::DataRingBuffer_Clear___VOID__I4,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_nanoFramework_Runtime_ISR_Core =
{
    "nanoFramework.Runtime.ISR.Core",
    0x9735116C,
    method_lookup,
    { 1, 0, 0, 0 }
};

// clang-format on
