//
// Copyright (c) .NET Foundation and Contributors
// See LICENSE file in the project root for full license information.
//
#include "nf_runtime_isr_core.h"

// clang-format off

static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_DeviceConfiguration::GetRequiredInterruptQueueSize___U2,
    NULL,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_DeviceConfiguration::GetRequiredAfterInterruptStackSize___U4,
    NULL,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_DeviceConfiguration::GetRequiredManagedTaskStackSize___U4,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::DoAllocateMemory___BOOLEAN__nanoFrameworkRuntimeISRInterpreterMemoryType__U4,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::AssignMemory___VOID__nanoFrameworkRuntimeISRInterpreterMemoryType__U4__SZARRAY_U1,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::AssignOffset___VOID__nanoFrameworkRuntimeISRInterpreterMemoryType__U4__U4,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::IsOffsetAssigned___BOOLEAN__nanoFrameworkRuntimeISRInterpreterMemoryType__U4,
    NULL,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::GetMemoryPointer___I4__nanoFrameworkRuntimeISRInterpreterMemoryType__U4,
    NULL,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::ReadManagedData___VOID__nanoFrameworkRuntimeISRInterpreterMemoryType__U4__I4__OBJECT__SZARRAY_U1,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::WriteManagedData___VOID__nanoFrameworkRuntimeISRInterpreterMemoryType__U4__I4__OBJECT__SZARRAY_U1,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::ReleaseMemory___VOID,
    NULL,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::DoStartServiceRoutine___VOID__nanoFrameworkRuntimeISROnManagedActivation__BOOLEAN,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::StopManagedActivatedServiceRoutine___VOID,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::EnableRTOSTask___VOID,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::DisableRTOSTask___VOID,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::Lock_GetMemorySize___U4,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::Lock_Initialize___VOID__I4,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::Lock_Dispose___VOID__I4,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::DataBuffer_GetMemorySize___U4__U4__U4,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::DataBuffer_Initialize___VOID__I4__U4__U4,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::DataRingBuffer_GetMemorySize___U4__U4__U4,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_ServiceRoutineManager::DataRingBuffer_Initialize___VOID__I4__U4__U4,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_NativeDataBuffer::ElementCount___U4,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_NativeDataBuffer::Add___VOID__OBJECT__SZARRAY_U1,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_NativeDataBuffer::Set___VOID__U4__OBJECT__SZARRAY_U1,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_NativeDataBuffer::Get___VOID__U4__OBJECT__SZARRAY_U1,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_NativeDataBuffer::Clear___VOID,
    NULL,
    NULL,
    NULL,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_NativeDataRingBuffer::BufferIsEmpty___BOOLEAN,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_NativeDataRingBuffer::Push___BOOLEAN__OBJECT__SZARRAY_U1__BOOLEAN,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_NativeDataRingBuffer::Peek___BOOLEAN__OBJECT__SZARRAY_U1,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_NativeDataRingBuffer::Pop___BOOLEAN__OBJECT__SZARRAY_U1,
    Library_nf_runtime_isr_core_nanoFramework_Runtime_ISR_NativeDataRingBuffer::Clear___VOID,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_nanoFramework_Runtime_ISR_Core =
{
    "nanoFramework.Runtime.ISR.Core",
    0xEC66A3FF,
    method_lookup,
    { 1, 0, 0, 0 }
};

// clang-format on
